# -indexing

In [5]:
# make a sting
a= "Samosa Pakora"
a

'Samosa Pakora'

In [6]:
a

'Samosa Pakora'

In [9]:
a[1]

'a'

In [12]:
a.find("S")

0

In [4]:
a[1]

'a'

In [5]:
a[3]

'o'

In [6]:
# length of  indices
len(a)

13

In [7]:
a[0]

'S'

In [8]:
a[1]

'a'

In [9]:
a[3]

'o'

In [10]:
a[12]

'a'

In [11]:
a[0:5]

'Samos'

In [12]:
# the last index is exclusive
a[0:13]

'Samosa Pakora'

In [13]:
a[-2]

'r'

In [14]:
a[-6:13]

'Pakora'

In [15]:
food = "Biryani"
food

'Biryani'

## sting methods

In [16]:
food

'Biryani'

In [17]:
len(food)

7

In [18]:
# capitalize every element
food.capitalize()

'Biryani'

In [19]:
#uppercase letters
food.upper()

'BIRYANI'

In [20]:
#lowercase letters
food.lower()

'biryani'

In [21]:
#replace
food.replace("B","Sh")

'Shiryani'

In [22]:
# counting a specific alphabet in a string
name = "baba_aammar with Dr Aammar tufail"
name

'baba_aammar with Dr Aammar tufail'

In [23]:
name.count("a")

8

### - find an index number in string

In [24]:
name ="baba_aammar with Dr Aammar Tufail"
name

'baba_aammar with Dr Aammar Tufail'

In [25]:
name.find("D")

17

In [26]:
### - how to split a string
food = " I love samosa, pakora,raita, biryani and karahi"
food

' I love samosa, pakora,raita, biryani and karahi'

In [27]:
food.split(",")

[' I love samosa', ' pakora', 'raita', ' biryani and karahi']

# Basic Data Structure in Python
## 1- Tupil
## 2- List
## 3- Dictionaries
## 4- Set

## 1- Tuples
- order collecton of elements
-  encolsed in () round brackest / paranthesis
- different kind of elements can be stored
- once elements are stored you cannot change them (unmutateable)

In [28]:
tup1 = (1, "Python", True, 2.5)
tup1

(1, 'Python', True, 2.5)

In [29]:
#type of tuple
type(tup1)

tuple

### - Indexing in tuple

In [30]:
tup1[1]

'Python'

In [31]:
tup1[2]

True

In [32]:
#last elements is exclusive
tup1[0:3]

(1, 'Python', True)

In [33]:
#count of elemts in tuple
len(tup1)

4

In [34]:
tup2 = (2, "babaAammar", 3.5, False)
tup2

(2, 'babaAammar', 3.5, False)

In [35]:
#concatenate (to add two tuple or more)
tup1+tup2

(1, 'Python', True, 2.5, 2, 'babaAammar', 3.5, False)

In [36]:
tup1*3+ tup2

(1,
 'Python',
 True,
 2.5,
 1,
 'Python',
 True,
 2.5,
 1,
 'Python',
 True,
 2.5,
 2,
 'babaAammar',
 3.5,
 False)

In [37]:
tup3 = (20,50,30,60,79,85)
tup3

(20, 50, 30, 60, 79, 85)

In [38]:
#minimum
min(tup3)

20

In [39]:
#maximum
max(tup3)

85

In [40]:
tup3*2

(20, 50, 30, 60, 79, 85, 20, 50, 30, 60, 79, 85)

In [41]:
tup3.count(20)


1

In [42]:
tup3.index(85)

5

## - List
- ordered collection of elemnts
- enclosed in [] square barces / brackest
- mutateable, you can change the value


In [43]:
list1 = [2, "babaAammar", False]
list1

[2, 'babaAammar', False]

In [44]:
type(list1)

list

In [45]:
len(list1)

3

In [46]:
list1[2]

False

In [47]:
list2 = [3, 5, "Aammar", "Codanics", 478, 53.2, False]
list2

[3, 5, 'Aammar', 'Codanics', 478, 53.2, False]

In [48]:
list1+list2

[2, 'babaAammar', False, 3, 5, 'Aammar', 'Codanics', 478, 53.2, False]

In [49]:
list1*2

[2, 'babaAammar', False, 2, 'babaAammar', False]

In [50]:
list1

[2, 'babaAammar', False]

In [51]:
list1.reverse()
list1

[False, 'babaAammar', 2]

In [52]:
list1.append("Codanics Youtube Channel")
list1

[False, 'babaAammar', 2, 'Codanics Youtube Channel']

In [53]:
list1.count('babaAammar')


1

In [54]:
list3 = [20,30,50,10,11,886,422,45]
list3

[20, 30, 50, 10, 11, 886, 422, 45]

In [55]:
len(list3)

8

In [56]:
#sorting a list
list3.sort()
list3

[10, 11, 20, 30, 45, 50, 422, 886]

In [57]:
list3*3

[10,
 11,
 20,
 30,
 45,
 50,
 422,
 886,
 10,
 11,
 20,
 30,
 45,
 50,
 422,
 886,
 10,
 11,
 20,
 30,
 45,
 50,
 422,
 886]

In [58]:
lists = list1+list2
lists

[False,
 'babaAammar',
 2,
 'Codanics Youtube Channel',
 3,
 5,
 'Aammar',
 'Codanics',
 478,
 53.2,
 False]

In [59]:
list3.append("Amir")
list3

[10, 11, 20, 30, 45, 50, 422, 886, 'Amir']

In [60]:
list3.count(20)


1

In [61]:
list3.copy()
list3

[10, 11, 20, 30, 45, 50, 422, 886, 'Amir']

In [62]:
list3.extend("Amir")
list3

[10, 11, 20, 30, 45, 50, 422, 886, 'Amir', 'A', 'm', 'i', 'r']

In [63]:
list3.index(422)

6

In [64]:
list3.insert(10, 11)
list3

[10, 11, 20, 30, 45, 50, 422, 886, 'Amir', 'A', 11, 'm', 'i', 'r']

## -3 Dictionaries
- an unordered collection of elements
- Key ad Value
- curly braces {} / brackets
- Mutateable/ change the values

In [65]:
#Food and their prices
food1 = {"Samosa":30,"Raita":20,"Pakora":100, "Salad":50, "Chicken Rolls":30 }
food1


{'Samosa': 30, 'Raita': 20, 'Pakora': 100, 'Salad': 50, 'Chicken Rolls': 30}

In [66]:
type(food1)

dict

In [67]:
#extract data
keys1 = food1.keys()
keys1

dict_keys(['Samosa', 'Raita', 'Pakora', 'Salad', 'Chicken Rolls'])

In [68]:
values1 = food1.values()
values1

dict_values([30, 20, 100, 50, 30])

In [69]:
#adding element
food1["tikki"]=10
food1

{'Samosa': 30,
 'Raita': 20,
 'Pakora': 100,
 'Salad': 50,
 'Chicken Rolls': 30,
 'tikki': 10}

In [70]:
#update the values
food1["tikki"]=15
food1

{'Samosa': 30,
 'Raita': 20,
 'Pakora': 100,
 'Salad': 50,
 'Chicken Rolls': 30,
 'tikki': 15}

In [71]:
food2= {"Dates":30, "Chocolates":200, "Swayyan":1000}
food2

{'Dates': 30, 'Chocolates': 200, 'Swayyan': 1000}

In [72]:
#concatenate
food1.update(food2)

In [73]:
food1

{'Samosa': 30,
 'Raita': 20,
 'Pakora': 100,
 'Salad': 50,
 'Chicken Rolls': 30,
 'tikki': 15,
 'Dates': 30,
 'Chocolates': 200,
 'Swayyan': 1000}

## 4- Sets
- Unordered and unindexed
- curly braces {}
- No duplicates allowed


In [74]:
s1 = {1, 2.2, 5.2, "Aammar", "Codanics", "Faisalabad", True}
s1

{1, 2.2, 5.2, 'Aammar', 'Codanics', 'Faisalabad'}

In [75]:
#adding elenent
s1.add("Aammar1")

In [76]:
s1

{1, 2.2, 5.2, 'Aammar', 'Aammar1', 'Codanics', 'Faisalabad'}

In [77]:
#removing element
s1.remove("Aammar1")
s1

{1, 2.2, 5.2, 'Aammar', 'Codanics', 'Faisalabad'}

In [78]:
#copying of set
s1.copy()

{1, 2.2, 5.2, 'Aammar', 'Codanics', 'Faisalabad'}

In [79]:
s2 = {1, 35, "Amir"}
s2

{1, 35, 'Amir'}

In [80]:
#taking difference of two sets
s2.difference(s1)

{35, 'Amir'}

In [81]:
#update set after taking difference
s2.difference_update(s1)
s2

{35, 'Amir'}

In [82]:
s2.discard(35)
s2

{'Amir'}

In [83]:
#taking intersection of two sets
s2.intersection(s1, s2)

set()

In [84]:
#update the set after intersction 
s2.intersection_update(s1)
s2

set()

In [85]:
#if two sets have any element in common then true otherwise false
s2.isdisjoint(s1)

True

In [86]:
#checking if one set is subset of another set
s2.issubset(s1)

True

In [87]:
# checking if one set is super set of other set
s2.issuperset(s1)

False

In [89]:
# removes random element from set and print its value
s1.pop()

1

In [90]:
#method returns all the items present in given sets, except the items in their intersections.
s1.symmetric_difference(s2)

{2.2, 5.2, 'Aammar', 'Codanics', 'Faisalabad'}

In [92]:
# updates set  with the items common to other sets e,g A and B
s1.symmetric_difference_update(s2)
s1

{2.2, 5.2, 'Aammar', 'Codanics', 'Faisalabad'}

In [94]:
s1

{2.2, 5.2, 'Aammar', 'Codanics', 'Faisalabad'}

In [96]:
s2={1, 3,5}
s2

{1, 3, 5}

In [97]:
#taking union of both sets
s2.union(s1)

{1, 2.2, 3, 5, 5.2, 'Aammar', 'Codanics', 'Faisalabad'}

In [99]:
#updates one set after the items of 2nd set is added to first set
s1.update(s2)
s1

{1, 2.2, 3, 5, 5.2, 'Aammar', 'Codanics', 'Faisalabad'}

In [104]:
import numpy as np
a=np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [105]:
b=np.zeros(2)
b

array([0., 0.])

In [107]:
np.pi

3.141592653589793

In [108]:
f=np.arange(2,30)
f

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])