# numpy practice session

In [1]:
#import this library in j.notebook

In [2]:
#import this library un j.notebook
import numpy as np

# creating an usin numpy library

In [3]:
food =np.array(["Pakora", "Samosa", "Raita"])
food

array(['Pakora', 'Samosa', 'Raita'], dtype='<U6')

In [4]:
prices = np.array([5,5,5])
prices

array([5, 5, 5])

In [5]:
type(prices)

numpy.ndarray

In [6]:
type(food)

numpy.ndarray

In [7]:
len(prices)

3

In [8]:
len(food)

3

In [9]:
prices[0:]

array([5, 5, 5])

In [10]:
food[1]

'Samosa'

In [11]:
prices.mean()

5.0

In [12]:
#zeroes
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [13]:
# ones
np.ones(5)

array([1., 1., 1., 1., 1.])

In [14]:
#empty
np.empty(5)

array([1., 1., 1., 1., 1.])

In [16]:
#range
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
#specify
np.arange(2,20)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [18]:
#specific interval
np.arange(2,20,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [19]:
#table of 5
np.arange(0,55,5)

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [20]:
#linespace
np.linspace(1,10,num=5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [21]:
#specify your data type
np.ones(50, dtype=np.int64)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1], dtype=int64)

In [22]:
np.ones(50, dtype=np.float64)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

# Array functions

In [23]:
a=np.array([10,12,15,2,4,6,100,320,0.5,10.3])
a

array([ 10. ,  12. ,  15. ,   2. ,   4. ,   6. , 100. , 320. ,   0.5,
        10.3])

In [24]:
a.sort()
a

array([  0.5,   2. ,   4. ,   6. ,  10. ,  10.3,  12. ,  15. , 100. ,
       320. ])

In [25]:
b=np.array([10.2,3.2,35.6,91.6])
b

array([10.2,  3.2, 35.6, 91.6])

In [26]:
c=np.concatenate((a,b))
c

array([  0.5,   2. ,   4. ,   6. ,  10. ,  10.3,  12. ,  15. , 100. ,
       320. ,  10.2,   3.2,  35.6,  91.6])

In [27]:
c.sort()
c

array([  0.5,   2. ,   3.2,   4. ,   6. ,  10. ,  10.2,  10.3,  12. ,
        15. ,  35.6,  91.6, 100. , 320. ])

# 2-D arrays

In [33]:
a= np.array([[4,5], [2,1]])
a

array([[4, 5],
       [2, 1]])

In [30]:
b=np.array([[6,7],[7,8]])
b

array([[6, 7],
       [7, 8]])

In [34]:
c=np.concatenate((a,b), axis=0)
c

array([[4, 5],
       [2, 1],
       [6, 7],
       [7, 8]])

In [35]:
c=np.concatenate((a,b), axis=1)
c

array([[4, 5, 6, 7],
       [2, 1, 7, 8]])

# 3-D Array

In [36]:
b=np.array([[5,6,7],[8,9,10],[10,11,12]])
b

array([[ 5,  6,  7],
       [ 8,  9, 10],
       [10, 11, 12]])

In [37]:
b.ndim

2

In [38]:
#size (number of elements)
b.size

9

In [39]:
b.shape

(3, 3)

In [48]:
a= np.arange(9) #3x3=9
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [54]:
b=b.reshape(3,3)
b

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [58]:
#reshape
np.reshape(a, newshape=(1, 9), order='c')

array([[0, 1, 2, 3, 4, 5, 6, 7, 8]])

In [62]:
# Convert 1D into 2D
a=np.array([1,2,3,4,5,6,7,8,9])
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [63]:
a.shape

(9,)

In [64]:
#ROWWISE
b=a[np.newaxis,:]
b

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [65]:
b.shape

(1, 9)

In [67]:
#columnwise
c=a[:,np.newaxis]
c

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [69]:
#slicing
a[2:9]

array([3, 4, 5, 6, 7, 8, 9])

In [70]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [71]:
a*6

array([ 6, 12, 18, 24, 30, 36, 42, 48, 54])

In [72]:
a+6

array([ 7,  8,  9, 10, 11, 12, 13, 14, 15])

In [73]:
a.sum()

45

In [74]:
a.mean()

5.0

In [75]:
np.sort(a)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [77]:
a.sort()
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])